FROM nginx:alpine

# Copy the NGINX configuration file for the order service
COPY ./configs/nginx/order-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the order service
COPY ./data/service-responses/order-nginx/ /usr/share/nginx/html/

# Expose the port on which the order service will run
EXPOSE 8082

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]