FROM nginx:alpine

# Copy the NGINX configuration file for the catalog service
COPY ./configs/nginx/catalog-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the catalog service
COPY ./data/service-responses/catalog-nginx/ /usr/share/nginx/html/

# Expose the port on which the catalog service will run
EXPOSE 8081

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]