FROM nginx:alpine

# Copy the NGINX configuration file for the notify service
COPY ./configs/nginx/notify-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the notify service
COPY ./data/service-responses/notify-nginx/ /usr/share/nginx/html/

# Expose the port on which the notify service will run
EXPOSE 8084

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]