FROM nginx:alpine

# Copy the NGINX configuration file for the payment service
COPY ./configs/nginx/payment-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the payment service
COPY ./data/service-responses/payment-nginx/ /usr/share/nginx/html/

# Expose the port on which the payment service will run
EXPOSE 8083

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]