FROM nginx:alpine

# Copy the NGINX configuration file for the analytics service
COPY ./configs/nginx/analytics-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the analytics service
COPY ./data/service-responses/analytics-nginx/ /usr/share/nginx/html/

# Expose the port on which the analytics service will run
EXPOSE 8085

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]