FROM nginx:alpine

# Copy the NGINX configuration file for the discovery service
COPY ./configs/nginx/discovery-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the discovery service
COPY ./data/service-responses/discovery-nginx/ /usr/share/nginx/html/

# Expose the port on which the discovery service will run
EXPOSE 8500

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]