FROM nginx:alpine

# Copy the NGINX configuration file for the user service
COPY ./configs/nginx/user-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the service responses for the user service
COPY ./data/service-responses/user-nginx/ /usr/share/nginx/html/

# Expose the port on which the user service will run
EXPOSE 8080

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]